jobs:
- job: BUILD_MAC_PROJECTS
  condition: and(eq(variables.build_deps, false), eq(variables.build_mac, true))
  dependsOn: DOWNLOAD_SRC_TREE

  strategy:
    matrix:
      NANOVG:
        graphics: 'NANOVG'
      # CAIRO:
      #   graphics: 'CAIRO'
      # LICE:
      #   graphics: 'LICE'
      # AGG:
      #   graphics: 'AGG'

  pool:
    vmImage: 'macos-10.13'

  steps:
  - checkout: none

  - template: azure-get_src.yml

  - template: azure-projects.yml
    parameters:
      platform: azure-project-mac.yml
      graphics: $(graphics)

- job: BUILD_WIN_PROJECTS
  condition: and(eq(variables.build_deps, false), eq(variables.build_win, true))
  dependsOn: 
    - DOWNLOAD_SRC_TREE
    - BUILD_WIN_AAX_LIBS

  strategy:
    matrix:
      NANOVG:
        graphics: 'NANOVG'
      # CAIRO:
      #   graphics: 'CAIRO'
      # LICE:
      #   graphics: 'LICE'
      # AGG:
      #   graphics: 'AGG'

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - checkout: none

  - template: azure-get_src.yml

  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: 'DEPS_AAX_LIB_WIN'
      targetPath: 'Dependencies/IPlug/AAX_SDK/Libs/'

  - template: azure-projects.yml
    parameters:
      platform: azure-project-win.yml
      graphics: $(graphics)

- job: BUILD_WEB_PROJECTS
  condition: and(eq(variables.build_deps, false), eq(variables.build_web, true))
  dependsOn: DOWNLOAD_SRC_TREE

  strategy:
    matrix:
      NANOVG:
        graphics: 'NANOVG'
      CANVAS:
        graphics: 'CANVAS'

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - checkout: none

  - bash: |
      git clone https://github.com/emscripten-core/emsdk.git
      cd emsdk
      ./emsdk install latest
      ./emsdk activate latest
    displayName: Install emscripten

  - template: azure-get_src.yml

  - template: azure-projects.yml
    parameters:
      platform: azure-project-web.yml
      graphics: $(graphics)